### PR TITLE
Add coveralls badge

### PR DESCRIPTION
**Pull request by madbence**
You can enable the badge on [coveralls.io](https://coveralls.io)

### CODE REVIEW

**Comment by madbence** [comment]
Build fails because it needs #12

**Comment by brentropy** [comment]
I have been using Code Climate for coverage instead of coveralls since I am already using if for code quality. Thanks for the pull request though.

**Comment by madbence** [comment]
Sorry, I thought that code climate cannot track coverage :innocent: , nice lib btw :+1:!

**Comment by brentropy** [comment]
Thanks. I am glad you like it!

**Pull request closed without merging**
