### PR TITLE
Added close and done methods to the channel with a close example.

### PR DESCRIPTION
**Pull request by brentropy**
I am putting this in as a pull request so anyone who is willing to join in on the discussion can weigh in on how this might be implemented.

Go's channels, which chan is loosely based on, can be closed. This branch is an attempt to add similar functionality to chan. There are now two methods added to the channel.

``` javascript
ch.close(); // This will prevent values from being added to the channel
ch.done();  // Returns true only if the channel is closed and empty
```

The problem that I am dealing with is how to handle pending callbacks/yields when the channel is closed. This is how it works in Go:

> After the last value has been received from a closed channel c, any receive from c will succeed without blocking, returning the zero value for the channel element. The form `x, ok := <-c` will also set ok to false for a closed channel.

Since Go is statically typed, the values for a channel must be of the type declared when creating the channel. The channel returns the zero value for that type. Go also has multiple return values. The channel returns a second boolean value indicating if the value was a zero value due to the channel being closed.

As of right now the pending yields return `undefined`, but I am not sure that is the right decision. The other option would be to return an `Error` that would be thrown in the `co` instance and handle this with a `try/catch`.

Does anyone have an opinion of what would make more sense or other ideas?

### CODE REVIEW

**Comment by jonathanong** [comment]
i don't think it's possible for chan to handle pending callbacks correctly because it doesn't know how to keep track of them (unless you change the API, but i like it the way it is). so i created my own channel library that does: https://github.com/cojs/archan. 

i'm using chan for this: https://github.com/cojs/busboy

**Comment by braindev** [comment]
I think having a cardinal value to show a channel is closed is the right way to go for a language like javascript.  Clojure does a similar thing in it's core.async when you pull from a closed channel you get back nil.  I _believe_ you are not allowed to put nil on a channel.  Whatever the cardinal value is for a closed channel ( null undefined) it should not be allowed to be put on to a channel.  You need to be able to tell the difference between a closed and open channel receive.  Go doesn't need the cardinal value b/c receive can return two values.

:eyes:

**Comment by brentropy** [comment]
Thanks for the feedback. 

@braindev, I really like the cardinal value idea, but what if rather than limiting the ability to put `null` or `undefined` on a channel the cardinal value is an empty object. Since `{} !== {}` there could never be case where the value put on the channel is the same as the cardinal value. The empty object would be accessible from the channel for comparison.

``` javascript
// ...
var value = yield ch;
if (value !== ch.empty) {
  // do something
}
// ...
```

Having it be an empty object would also offer some more forgiveness if someone does not check for an empty value.

With `undefined` or `null`:

``` javascript
var value = yield ch;
console.log(value.foo); // Throws TypeError or ReferenceError
```

With `{}`:

``` javascript
var value = yield ch;
console.log(value.foo) // -> undefined
```

Taking it one step further the cardinal value could be an empty array. This would have all of the same advantages as an empty object, but would have the `Array.prototype` to offer more forgiveness in cases when the expected value is an array.

With `[]`:

``` javascript
var value = yield ch;
console.log(value.foo) // -> undefined
value.forEach(function(val) { console.log(val); }); // does nothing
```

Obviously it would still be a good idea to compare the value against `ch.empty` if there is a chance the channel could be closed while it is waiting to receive a value. Any thoughts on this?

**Comment by brentropy** [comment]
I settled on the empty value being an object to avoid collisions, but I made the type of object optionally configurable on a per channel basis.

``` javascript
var ch;

/**
 * Channel created with optional type constructor.
 */

ch = chan(Array);
ch.empty instanceof Array;  // -> true
ch.length; // -> 0

ch = chan(Number);
ch.empty.valueOf(); // -> 0

/**
 * Channel created with object value to be used directly as the empty value.
 * Useful for constructors with required arguments
 */

ch = chan(new Buffer(0));
ch.empty instanceof Buffer; // -> true
ch.empty.toString(); // -> ''
```

If no argument is given to the `chan()` function the constructor used for the empty value will default to `Object`. If a primitive value is used the constructor will default to `Object` just as if no value was given. The empty value _cannot_ be a primitive value.

**Pull request merged**
